cndt2021のLPを移植
cloudnativedaysjp/website pull request #20
Opened 2021-06-13 10:17 UTC by maktak1995

* ひとまず公開できるようにhttps://cloudnativedays.jp/の内容をトップページに移植する
* まとめて削除できるようになるべく独立したコンポーネントとして作る

2021-06-15 02:43 UTC, maktak1995 commented
PRがクソデカになってしまって申し訳ないです...
基本的には今出ているLPをまるっと移植しただけです

2021-06-19 03:23 UTC, jacopen commented
```\2021-06-14T14:06:13.708Z [INFO]: info  - Using webpack 4. Reason: future.webpack5 option not enabled https://nextjs.org/docs/messages/webpack5
2021-06-14T14:06:14.027Z [INFO]: info  - using build directory: /codebuild/output/src467802912/src/website/.next
2021-06-14T14:06:14.029Z [INFO]: info  - Copying "static build" directory
2021-06-14T14:06:14.031Z [INFO]: info  - No "exportPathMap" found in "next.config.js". Generating map from "./pages"
2021-06-14T14:06:14.032Z [WARNING]: Error: Image Optimization using Next.js' default loader is not compatible with `next export`.
                                    Possible solutions:
                                    - Use `next start` to run a server, which includes the Image Optimization API.
                                    - Use any provider which supports Image Optimization (like Vercel).
                                    - Configure a third-party loader in `next.config.js`.
                                    - Use the `loader` prop for `next/image`.
                                    Read more: https://nextjs.org/docs/messages/export-image-api
                                    at /codebuild/output/src467802912/src/website/node_modules/next/dist/export/index.js:14:785
                                    at async Span.traceAsyncFn (/codebuild/output/src467802912/src/website/node_modules/next/dist/telemetry/trace/trace.js:5:584)
2021-06-14T14:06:14.046Z [WARNING]: error Command failed with exit code 1.
2021-06-14T14:06:14.047Z [INFO]: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2021-06-14T14:06:14.056Z [ERROR]: !!! Build failed
2021-06-14T14:06:14.056Z [ERROR]: !!! Non-Zero Exit Code detected
2021-06-14T14:06:14.057Z [INFO]: # Starting environment caching...
2021-06-14T14:06:14.057Z [INFO]: # Uploading environment cache artifact...
2021-06-14T14:06:14.220Z [INFO]: # Environment caching completed
Terminating logging...
```

こんな感じでAmplifyのBuildが失敗していた。むむー？

2021-06-19 03:25 UTC, jacopen commented
https://github.com/aws-amplify/amplify-js/issues/7547

なるほど、SSGのときはImageコンポーネントが使えないと

2021-06-19 03:29 UTC, jacopen commented
手元でyarn exportしても同様のエラーが発生した。
SSGでいけたほうがいいかなーと思うので、yarn export通るような形にしてもらったほうがいいかも

2021-06-19 03:29 UTC, jacopen requested changes
yarn exportできるように変更おねしゃす！

2021-06-19 14:36 UTC, maktak1995 commented
@jacopen 
修正完了いたしました！amplifyでもちゃんと見れるようになりました！ご確認ください

2021-06-23 18:36 UTC, jacopen approved these changes
よさげ～

2021-06-23 18:36 UTC, merged